### ISSUE TITLE
Problem with "Ignore words filter"

### ISSUE THREAD

**Issue by wcz-txp** [phpbb-seo/meta#1]
When I switch on "Ignore words filter" then I run in this error.

```
PHP Fatal error:  Uncaught Error: Cannot assign by reference to overloaded object in /var/www/forum/ext/phpbbseo/meta/core.php:432
Stack trace:
#0 /var/www/forum/ext/phpbbseo/meta/core.php(381): phpbbseo\meta\core->make_keywords(Array)
#1 /var/www/forum/ext/phpbbseo/meta/event/listener.php(69): phpbbseo\meta\core->build_meta()
#2 [internal function]: phpbbseo\meta\event\listener->core_page_footer(Object(phpbb\event\data), 'core.page_foote...', Object(phpbb\event\dispatcher))
#3 /var/www/forum/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(phpbb\event\data), 'core.page_foote...', Object(phpbb\event\dispatcher))
#4 /var/www/forum/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'core.page_foote...', Object(phpbb\event\data))
#5 /var/www/forum/phpbb/event/dispatcher.php(62): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('core.page_foote...', Object(phpbb\event\data))
#6 /var/www/forum/phpbb/event/disp in /var/www/forum/ext/phpbbseo/meta/core.php on line 432
```

Without this filter phpseo/meta seems to work more or less in phpbb 3.2.2 with php 7.0.27 ...

**Comment by Leinad4Mind** [comment]
The file:
this->user->lang_path}{$this->user->lang_name}/search_ignore_words.$this->php_ext

Doesnt exist no more on 3.2 thats why it bugs...

You can add the language file back in. Just grab it from a 3.1 language pack and thats it...

**Comment by wcz-txp** [comment]
Thanks, that's of course another work around.
